# -*- coding: utf-8 -*-
"""CSE110 Lab Assignment 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LDfFEsrC4CQK0M5ccMA-u-06tVUPpjAc

#Task 1
"""

a_tuple = ("The Institute", ("Best Mystery & Thriller", "The Silent Patient", 68821), 75717, [1, 2, 3, 400, 5, 6, 7], ("Best Fiction", "The Testaments", 98291))
print(a_tuple[3][3])

"""#Task 2"""

tup = (-10, 20, 25, 30, 40)
if len(tup)<4:
  print('Not Possible')
else:
  print(tup[2:-2])

"""#Task 3"""

book_info = (
("Best Mystery & Thriller","The Silent Patient",68,821),
("Best Horror","The Institute",75,717),
("Best History & Biography","The five",31,783 ),
("Best Fiction","The Testaments",98,291)
)
print('Size of the tuple is:',len(book_info))
for i in book_info:
  print(i)

"""#Task 4"""

book_info = (
("Best Mystery & Thriller","The Silent Patient",68821),
("Best Horror","The Institute",75717),
("Best History & Biography","The five",31783 ),
("Best Fiction","The Testaments",98291)
)
for i in book_info:
  category, book, vote = i
  print(f"{book} won the '{category}' category with {vote} votes")

"""#Task 5"""

tup = (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
num = int(input("Enter a number: "))
c = 0
for i in tup:
  if i==num:
    c += 1
print(f'{num} appears {c} times in the tuple')

"""#Task 6"""

tup = (10, 20, 30, 40, 50, 60)
lst = list(tup)
lst.reverse()
print(tuple(lst))

tup = (10, 20, 30, 40, 50, 60)
lst = list(tup)
lst2=[]
for i in lst:
  lst2=[i]+lst2
print(tuple(lst2))

"""#Task 7"""

d1 = {'Harry':15, 'Draco':8, 'Nevil':19}
d2 = {'Ginie':18, 'Luna': 14}
d3 = {}
for key, value in d1.items():
  d3[key] = value
for key, value in d2.items():
  d3[key] = value
print(d3)

d1 = {'Harry':15, 'Draco':8, 'Nevil':19}
d2 = {'Ginie':18, 'Luna': 14}
d3 = d1
d3.update(d2)
print(d3)

"""#Task 8"""

l=[i for i in input('Enter a dictionary: ').split(', ')]
d={}
for i in l:
  x=i.split(':')
  key=x[0]
  value=int(x[1])
  d[key]=value
sum=0
for i,j in d.items():
  sum+=j
print('Average is',int(sum/len(d)))

d = {'Jon': 100, 'Dan': 200, 'Rob': 30, 'Ned': 110}
c = 0
s = 0
for val in d.values():
  s+=val
  c+=1
print(f'Average is {int(s/c)}.')

"""#Task 9"""

exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}
num = int(input("Enter a number: "))
d = {}
for key, val in exam_marks.items():
  if val>=num:
    d[key] = val
print(d)

exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}
num = int(input("Enter a number: "))
d = {}
for key, val in exam_marks.items():
  if val>=num:
    d.update({key: val})
print(d)

"""#Task 10"""

d = {'sci fi': 12, 'mystery': 15, 'horror': 8, 'mythology': 10, 'young_adult': 4, 'adventure':14}
max = 0
for i in d.values():
  max = i
  break
for key, val in d.items():
  if val>max:
    max = val
    genre = key
print(f"The highest selling book genre is '{genre}' and the number of books sold are {max}.")

"""#Task 11"""

s=input("Enter a string: ").lower()
d={}
for i in s:
  if i!=' ':
    if i not in d:
      d[i]=1
    else:
      d[i]+=1
print(d)

s = input("Enter a string: ")
x = ''
for i in s:
  if ord("A")<=ord(i)<=ord("Z"):
    x+=chr(ord(i)+32)
  else:
    x+=i
d = {}
c = 0
for i in x:
  if i!=' ':
    for j in x:
      if i==j:
        c+=1
    d.update({i: c
              })
    c=0
print(d)

"""#Task 12"""

dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
sum = 0
for i in dict_1.values():
  for j in i:
    sum+=1
print(sum)

"""#Task 13"""

list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]
d = {}
for i in list_1:
  s, n = i
  if s not in d:
    d[s]=[n]
  else:
    d[s].append(n)
print(d)

"""#Task 14 (Tracing)"""

dict1 = {'a':59 , 'b':-82 , 'c':5 , 'd':-81 , 'e':53}
for i in dict1:
    j = 0
    k = 22
    while j < 5:
        if j % 2 == 0:
            k = dict1[i] + j - (8 + k % 6) / 3
            dict1[i] = dict1[i]+ int(k)
        else:
            k = dict1[i] + j - (6 - k % 8) * 3
            dict1[i] = dict1[i] - int(k)
        j += 1
    print(int(k))
    print(i + " -> " + str(dict1[i]))

"""#Task 15 (Ungraded)"""

l1 = [(2, 3), (4, 5), (6, 7), (2, 8)]
l2 = []
for i in l1:
  a,b=i
  l2.append(a*b)
print(l2)

"""#Task 16 (Ungraded)"""

a_tuple = ( [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12])
s = input()
l = []
for i in a_tuple:
  i[2]=s
  l.append(i)
print(tuple(l))

"""#Task 17 (Ungraded)"""

my_dictionary = {'c1':'Red', 'c2':'Green', 'c3':None, 'd4':'Blue', 'a5':None}
d = {}
for key, val in my_dictionary.items():
  if val!=None:
    d[key]=val
print(d)

"""#Task 18 (Ungraded)"""

d1 = {'a' : 6, 'b' : 7, 'c' : 9,
      'd' : 8, 'e' : 11, 'f' : 12, 'g' : 13}
s = input("Enter two number seperated by a comma and space: ")
s = s.split(', ')
l = []
for i in s:
  l.append(int(i))
lw = l[0]
up = l[1]
d2={}
for key, val in d1.items():
  if lw<=val<up:
    d2[key]=val
print(d2)

"""#Task 19 (Ungraded)"""

l = [(20, 80), (31, 80), (1, 22), (88, 11), (27, 11)]
d={}
for i in l:
  x,y=i
  if y not in d:
    d[y]=[i]
  else:
    d[y].append(i)
print(d)

"""#Task 20 (Ungraded)"""

s=input('String: ')
t=''
for i in s:
  if i!='.':
    t+=i
t=t.split(' ')
s1=input('List of characters: ')[1:-1]
s2=''
for i in s1:
  if i!="'":
    s2+=i
l=[i for i in s2.split(', ')]
print('Words in the given String:',t)
l2=[]
for i in t:
  if i not in l2:
    l2.append(i)
d={}
sum=0
for i in l2:
  for j in i:
    sum+=ord(j)
  x=sum%len(l)
  if l[x] not in d:
    d[l[x]]=[i]
  else:
    d[l[x]].append(i)
  sum=0
print('Answer:',d)